### ISSUE TITLE
yuque 2 obsidian 

### ISSUE THREAD

**Issue by ghost** [yuque-helper/yuque2book#12]
作者有没有用过 http://obsidian.md/
一个支持双向链接的本地存储笔记工具。
如果能高效的把语雀上的大部分文档转换成 md的格式，输入到obsdn里面，就比较方便了。
当然一篇一篇的输入到obsdn是没问题的，只不过速度太慢。

如果作者有兴趣可以用用obsdn，以及尝试写个转换程序。谢谢！

**Comment by cctv1005s** [comment]
没有喔，暂时没有相关的计划

**Comment by ghost** [comment]
先了解一下 obsidian，

**Comment by ghost** [comment]
test
