### ISSUE TITLE
能支持导出为markdown格式吗

### ISSUE THREAD

**Issue by MaplerStory** [yuque-helper/yuque2book#19]
有些时候需要对导出的备份文档重新做些编辑，现在导出html格式编辑不便

**Comment by lvgithub** [comment]
+1

**Comment by JayeLi** [comment]
+1

**Comment by YDTRINLEY** [comment]
+1 真是刚需~ 要语雀迁移到飞书 麻烦到头秃

**Comment by Silypie** [comment]
+1

**Comment by leojjj** [comment]
+1

**Comment by wsy1074** [comment]
+1

**Comment by wsy1074** [comment]
https://github.com/Ri0nXh/ScriptCode
希望能实现这样的功能

**Comment by cctv1005s** [comment]
这个 Issue pending 好久了，天猪提供了类似的 npm 包，请各位中文的用户参考：https://zhuanlan.zhihu.com/p/582287220
