### ISSUE TITLE
图片保存异常

### ISSUE THREAD

**Issue by Ran-Xing** [yuque-helper/yuque2book#25]
图片莫名其妙变多  部分图片无内容
有没有语雀转Markdown的工具推荐一下

**Comment by cctv1005s** [comment]
哪个文档的问题？

**Comment by aaq1adqwe** [comment]
应该是防盗链检测，有办法吗

**Comment by cctv1005s** [comment]
比较难解决，官方的防盗链的我不好去处理，三方文档可能存在这样的问题，如果我强行利用 cookie 下载下来可能会面临法律风险
