### ISSUE TITLE
依赖报错，望解答

### ISSUE THREAD

**Issue by innoseon** [yuque-helper/yuque2book#38]
![image](https://user-images.githubusercontent.com/90334906/205425645-0cfbe742-fa36-49e9-9e1d-a72e04b6232f.png)
npm install yuque2book -g一切正常 运行yuque2book （-v），后报错MODULE_NOT_FOUND后安装了nodejieba（因此使用nvm切换了node.js15 安装了nodejieba）
之后又报错缺少不明模块，如上图
想问一下作者使用的是哪一个版本，感谢

**Comment by innoseon** [comment]
15版本尝试无果后又切换了14版本 仍然是上图的结果

**Comment by innoseon** [comment]
![image](https://user-images.githubusercontent.com/90334906/205426447-01af3681-60b8-474f-ae10-aa4ad7bb49eb.png)

**Comment by innoseon** [comment]
后续：尝试在ubuntu上跑，nodev14一次成功

**Comment by cctv1005s** [comment]
有点厉害！
