### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by Hiwoniu** [yuque-helper/yuque2book#47]
'yuque2book' 不是内部或外部命令，也不是可运行的程序，
node  版本

C:\Users\Administrator>npm  -v
8.1.0

C:\Users\Administrator>node -v
v16.13.0
![Snipaste_2023-10-08_15-59-22](https://github.com/yuque-helper/yuque2book/assets/80250844/658d877c-e3e4-4583-b75c-5e142272890f)

**Comment by cctv1005s** [comment]
@Hiwoniu  应该是你的全局变量设置得不对，你可以试着 google 查一下这个问题，很多教程的，比如说下面这个，你可以试试：

https://zhuanlan.zhihu.com/p/127043172

**Comment by godwinnnnn** [comment]
npx yuque2book -t <token> <url>
试试这个，应该是环境变量设置问题。这个cmd直接在已经安装的模块里查找执行，应该是可以的。

> 'yuque2book' 不是内部或外部命令，也不是可运行的程序， node 版本
> 
> C:\Users\Administrator>npm -v 8.1.0
> 
> C:\Users\Administrator>node -v v16.13.0 ![Snipaste_2023-10-08_15-59-22](https://private-user-images.githubusercontent.com/80250844/273434182-658d877c-e3e4-4583-b75c-5e142272890f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODI4NzEsIm5iZiI6MTcwNDA4MjU3MSwicGF0aCI6Ii84MDI1MDg0NC8yNzM0MzQxODItNjU4ZDg3N2MtZTNlNC00NTgzLWI3NWMtNWUxNDIyNzI4OTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA0MTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NGY0MTg5MWQ5MjljNTRlM2MyNTJlZDk3ZmRkYWJlY2ZhZWJkYTg4ODZmMzY5NTE1MThmYzdiMmFmZWM2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LUX4it_-nYYx0XMS71isqcjhVy-TbtLFklNEAPN3YFY)
