### ISSUE TITLE
能否一个文档对应一个HTML，并且带图片，附件

### ISSUE THREAD

**Issue by ghost** [yuque-helper/yuque2book#5]
现在这命令是所有文档都是同一个HTML，能否换成一个文档一个HTML，并且带图片，附件。谢谢

**Comment by tangkaichuan** [comment]
我认为是 markdown 源文件会更好，可以在 html 里直接渲染 markdown

**Comment by ghost** [comment]
> 我认为是 markdown 源文件会更好，可以在 html 里直接渲染 markdown

HTML 格式通用，在webkit浏览器里就可以打开，比较方便，通用。
markdown各个软件支持的标注不同的，需要特定的软件，比如你从语雀上导出的mardown，不一定在别的markdown软件对应的上。

**Comment by tangkaichuan** [comment]
> > 我认为是 markdown 源文件会更好，可以在 html 里直接渲染 markdown
> 
> HTML 格式通用，在webkit浏览器里就可以打开，比较方便，通用。
> markdown各个软件支持的标注不同的，需要特定的软件，比如你从语雀上导出的mardown，不一定在别的markdown软件对应的上。

有很多相似的开源的 js 脚本用以在 html 中直接渲染，还是在浏览器打开，但是数据源是 markdown

**Comment by ghost** [comment]
现在他这脚本就是直接输出html的，你想让他再次转markdown吗？还是直接输出markdown ？ 

> 有很多相似的开源的 js 脚本用以在 html 中直接渲染，还是在浏览器打开，但是数据源是 markdown

**Comment by cctv1005s** [comment]
啥？你俩是同一个人在讨论吗？

**Comment by ghost** [comment]
> 啥？你俩是同一个人在讨论吗？

那个人好像删除了对话。哈哈
这个关闭吧。
