### ISSUE TITLE
Anywhere后，浏览器显示空白啊。

### ISSUE THREAD

**Issue by ghost** [yuque-helper/yuque2book#6]
![image](https://user-images.githubusercontent.com/16850883/79884057-41c14e80-8427-11ea-9ed3-074d6f4045a6.png)
![image](https://user-images.githubusercontent.com/16850883/79884094-4d147a00-8427-11ea-9e0f-184b70412fc6.png)

命令加了 -t, -l 参数，而且每个文档都获取成功了。

**Comment by ghost** [comment]
原来要用chrome才能显示出来。

**Comment by cctv1005s** [comment]
@steveyang331  你这啥浏览器？搜狗？

**Comment by ghost** [comment]
QQ 浏览器，用于看国内网页的。

知道原因了，输入IP，默认变成 IE内核了，
![image](https://user-images.githubusercontent.com/16850883/80782369-7f9d4000-8ba8-11ea-9d5f-46c371ab3df5.png)

或者把QQ的内核切换 chromium 内核。

用New edge和 Google Chrome 就可以了。

谢谢。
