### ISSUE TITLE
图片下载您能给点建议吗？

### ISSUE THREAD

**Issue by hu-qi** [yuque-helper/yuque2book#9]
感谢大佬分享工具！
刚使用了下，发现一个小小的问题，估计因为语雀cdn图片资源开了防盗的y原因还是https的缘故，本地访问时，图片资源报403。于是想到将图片也下载下来，您能给点实现思路的指导吗？
![image](https://user-images.githubusercontent.com/17986122/87921920-d599c980-caad-11ea-910b-734869458511.png)

**Comment by YangShuqing** [comment]
下载时加-l 参数就可以下载图片示例

**Comment by YangShuqing** [comment]
yuque2book -t your_token -l https://www.yuque.com/yuque/help

**Comment by cctv1005s** [comment]
> yuque2book -t your_token -l https://www.yuque.com/yuque/help

感谢大佬帮忙回复

**Comment by cctv1005s** [comment]
closed
